In [1]:
#data set form kaggle :link:  https://www.kaggle.com/competitions/fake-news/data?select=train.csv

import pandas as pd

# Load the dataset with the correct delimiter
df = pd.read_csv("train.csv")


In [2]:
df.head()

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1


In [3]:
x = df.drop('label', axis = 1) # ye sab mere independent feature hai

In [4]:
y = df['label']  # thats my output level

In [5]:
x

,id,title,author,text
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ..."
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...
...,...,...,...,...
20795,20795,Rapper T.I.: Trump a ’Poster Child For White S...,Jerome Hudson,Rapper T. I. unloaded on black celebrities who...
20796,20796,"N.F.L. Playoffs: Schedule, Matchups and Odds -...",Benjamin Hoffman,When the Green Bay Packers lost to the Washing...
20797,20797,Macy’s Is Said to Receive Takeover Approach by...,Michael J. de la Merced and Rachel Abrams,The Macy’s of today grew from the union of sev...
20798,20798,"NATO, Russia To Hold Parallel Exercises In Bal...",Alex Ansary,"NATO, Russia To Hold Parallel Exercises In Bal..."


In [6]:
y

0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 20800, dtype: int64

In [7]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [8]:
pip install tensorflow==2.18.0

Note: you may need to restart the kernel to use updated packages.


In [9]:
import tensorflow as tf
print(tf.__version__)


2.18.0


In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional

In [11]:
#vacobalury size
voc_size=5000

In [12]:
messages = x.copy()

In [13]:
messages

,id,title,author,text
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ..."
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...
...,...,...,...,...
20795,20795,Rapper T.I.: Trump a ’Poster Child For White S...,Jerome Hudson,Rapper T. I. unloaded on black celebrities who...
20796,20796,"N.F.L. Playoffs: Schedule, Matchups and Odds -...",Benjamin Hoffman,When the Green Bay Packers lost to the Washing...
20797,20797,Macy’s Is Said to Receive Takeover Approach by...,Michael J. de la Merced and Rachel Abrams,The Macy’s of today grew from the union of sev...
20798,20798,"NATO, Russia To Hold Parallel Exercises In Bal...",Alex Ansary,"NATO, Russia To Hold Parallel Exercises In Bal..."


In [14]:
import nltk
import re 
from nltk.corpus  import stopwords


In [15]:
pip install --upgrade nltk

Note: you may need to restart the kernel to use updated packages.


In [16]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\91979\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [17]:
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
import re

ps = PorterStemmer()  # instantiate the PorterStemmer
corpus = []

for i in range(0 , len(messages)):
    print(i)
    review = str(messages['title'][i])  # convert to string to avoid the error
    review = re.sub('[^a-zA-Z]', ' ', review)
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if word not in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [18]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'life life luxuri elton john favorit shark pictur stare long transcontinent flight',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'excerpt draft script donald trump q ampa black church pastor new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find hom

In [19]:
onehot_repr = [one_hot(words, voc_size) for words in corpus]
print(onehot_repr)

[[4054, 4332, 4432, 4538, 801, 3140, 428, 2666, 713, 1639], [2988, 2500, 4371, 3209, 1696, 3131, 4100], [1984, 1662, 3165, 2773], [902, 2262, 2660, 1625, 612, 880], [1776, 1696, 3508, 397, 2523, 4261, 1696, 997, 3820, 2329], [1951, 3790, 1658, 3279, 2748, 4043, 4883, 2724, 3573, 67, 146, 1511, 1404, 4695, 4100], [2181, 2181, 2942, 1770, 4001, 4037, 4978, 4403, 1884, 1589, 8, 684], [1799, 546, 1766, 371, 2791, 4805, 4756, 4059, 255, 1864, 200], [4710, 1447, 2299, 2835, 4043, 4122, 386, 3604, 4907, 3172, 255, 1864, 200], [4068, 4652, 4367, 304, 2711, 3170, 4043, 3987, 255, 1864, 200], [1504, 4544, 3215, 1493, 910, 767, 4285, 2383, 4043, 470], [3821, 180, 2927, 139, 596, 20, 257, 2809], [2671, 766, 609, 1546, 4780, 3190, 1034, 37, 1917, 771, 3154], [1625, 3166, 801, 767, 4043, 2711], [817, 2777, 4276, 1460, 4288, 431, 1688, 130, 680], [2694, 3129, 2864, 2411, 2905, 4958, 3352, 255, 1864, 200], [2545, 2571, 1081, 4711, 3320, 255, 1864, 200], [4027, 2966, 1110, 817, 2722, 483, 1930, 3894, 1

In [20]:
#Embedding presentation
sent_length = 20
embedded_docs = pad_sequences(onehot_repr , padding = 'pre', maxlen = sent_length)
embedded_docs


array([[   0,    0,    0, ..., 2666,  713, 1639],
       [   0,    0,    0, ..., 1696, 3131, 4100],
       [   0,    0,    0, ..., 1662, 3165, 2773],
       ...,
       [   0,    0,    0, ...,  255, 1864,  200],
       [   0,    0,    0, ..., 3957,  782, 3997],
       [   0,    0,    0, ..., 4882,  208, 2073]])

In [43]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

C:\Users\91979\OneDrive\Desktop\python.project\Annaconda\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [51]:
import numpy as np
x_final = np.array(embedded_docs)
y_final = np.array(y)

In [53]:
##train test split 
from sklearn.model_selection import train_test_split
x_train, x_test , y_train, y_test = train_test_split(x_final, y_final, test_size = 0.2, random_state = 23)

In [55]:
#model trainig 
model.fit(x_final, y_final, validation_data = (x_test, y_test), epochs = 10,batch_size = 32)

Epoch 1/10
650/650 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.8589 - loss: 0.3046 - val_accuracy: 0.9514 - val_loss: 0.1205
Epoch 2/10
650/650 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.9536 - loss: 0.1236 - val_accuracy: 0.9808 - val_loss: 0.0749
Epoch 3/10
650/650 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9731 - loss: 0.0763 - val_accuracy: 0.9875 - val_loss: 0.0500
Epoch 4/10
650/650 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9810 - loss: 0.0549 - val_accuracy: 0.9913 - val_loss: 0.0305
Epoch 5/10
650/650 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9903 - loss: 0.0327 - val_accuracy: 0.9966 - val_loss: 0.0169
Epoch 6/10
650/650 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.9935 - loss: 0.0193 - val_accuracy: 0.9962 - val_loss: 0.0154
Epoch 7/10
650/650 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9937 - loss: 0.0194 - val_accuracy: 0.9976 - val_loss: 0.0094
Epoch 8/10
650/650 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9965 - loss: 0.0105 - val_accuracy: 0

In [57]:
y_pred = model.predict(x_test)

130/130 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


In [81]:
import numpy as np

# If y_pred is a tuple, convert it to a numpy array
y_pred = np.array(y_pred)

# Now apply the threshold
y_pred = np.where(y_pred >= 0.5, 1, 0)

print(y_pred)


[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]]


In [87]:
print(f"Shape of y_test: {y_test.shape}")
print(f"Shape of y_pred: {y_pred.shape}")


Shape of y_test: (4160,)
Shape of y_pred: (2, 2068)


In [99]:
y_pred = model.predict(x_test)  # Make predictions on the test set
y_pred = (y_pred >= 0.5).astype(int)  # For binary classification, threshold predictions


130/130 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


In [103]:
y_pred = np.argmax(model.predict(x_test), axis=1)  # For multi-class classification


130/130 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


In [105]:
print(f"Length of y_test: {len(y_test)}")
print(f"Length of y_pred: {len(y_pred)}")


Length of y_test: 4160
Length of y_pred: 4160


In [111]:
from sklearn.metrics import confusion_matrix, accuracy_score
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)


[[2098    0]
 [2062    0]]


In [117]:
accuracy_score(y_test, y_pred)

0.5043269230769231